update ml example notebook
geo-engine/geoengine-python pull request #142
Opened 2023-07-12 20:55 UTC by jdroenner

2023-07-12 20:57 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update ML  Example Notebook to new Features](https://trello.com/c/hzGJNabH/1392-update-ml-example-notebook-to-new-features)

2023-07-13 06:05 UTC, ChristianBeilschmidt requested changes

2023-07-13 06:05 UTC, ChristianBeilschmidt commented on examples/s2_field_combination_extern_rf_train/nrw_crop_extern_s2_workflow_to_datasets_with_timeshift.ipynb
You've removed 4 (leaving 1-5), but the document still got headers 1-6.

2023-07-13 08:12 UTC, jdroenner commented on examples/s2_field_combination_extern_rf_train/nrw_crop_extern_s2_workflow_to_datasets_with_timeshift.ipynb
i put it back in

2023-07-13 10:42 UTC, ChristianBeilschmidt approved these changes

2023-07-13 10:47 UTC, merged