Update deps 2024 12 06
geo-engine/geoengine-python pull request #207
Opened 2024-12-06 14:23 UTC by jdroenner

2024-12-12 09:20 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Python](https://trello.com/c/xDS0IaIv/1780-update-python)

2024-12-12 09:38 UTC, ChristianBeilschmidt commented on tests/test_workflow_raster_stream.py
> +        return []
Für was ist das? Eher error?

2024-12-12 09:51 UTC, jdroenner commented on tests/test_wcs.py
> +            # TODO: Test with np.array_equal(?
Mir scheint, dass OWSLib in verschiedenen  Versionen verschiedene Felder in der Response hat. Deshalb kann man nicht mit equals testen. Ich teste hier auf das Subset welches wir erwarten. Das TODO kann man vermutlich rausnehmen.

2024-12-12 09:55 UTC, jdroenner commented on tests/test_wcs.py
> +                    # 'crs': " TODO: could be "CRS.from_wkt(..." or "CRS.from_epsg(..."
nicht mit der aktuellen Range an OWSLib Versionen. Man muss entweder Min hoch ziehen oder Max wieder absenken.
- `AREA_OR_POINT`:  gibt es nicht in der min_version. Sonst aber in allen, hier könnte man also min hoch ziehen.
- 'transform': ist in den neuen Versionen vom Type 'Affine'.
- 'crs': ist entweder 'CRS.from_wkt' oder 'CRS.from_epsg' je nach Version. Das sollte in der Praxis egal sein. Ist für den Test aber blöd.

2025-01-13 10:48 UTC, ChristianBeilschmidt requested changes

2025-01-13 10:48 UTC, ChristianBeilschmidt commented on tests/test_workflow_raster_stream.py
> +        return []
Aber sollte man dann nicht einen Fehler werfen? Leere Rückgabe ist ja irreführend.

2025-01-13 10:48 UTC, ChristianBeilschmidt commented on tests/test_wcs.py
> +            # TODO: Test with np.array_equal(?
Kann man das dann hier kurz erklären?

2025-01-13 10:48 UTC, ChristianBeilschmidt commented on setup.cfg
>  python_requires = >=3.9
Aber das RESPECT-Volume gibt es ja nicht normalerweise.

Vielleicht kannst du das mit dem neuen Testkram ausprobieren?

2025-01-24 11:37 UTC, jdroenner commented on tests/test_workflow_raster_stream.py
> +        return []
[1f34b9c](https://github.com/geo-engine/geoengine-python/pull/207/commits/1f34b9c425664a91879c2c1c422a0d8edd063f7c)

2025-01-24 11:37 UTC, jdroenner commented on tests/test_wcs.py
> +            # TODO: Test with np.array_equal(?
[d8e4768](https://github.com/geo-engine/geoengine-python/pull/207/commits/d8e4768a7edd364a1fbf54d6166bc20b1f63b64b)

2025-01-24 11:38 UTC, jdroenner commented on setup.cfg
>  python_requires = >=3.9
[c4aba92](https://github.com/geo-engine/geoengine-python/pull/207/commits/c4aba92cd6dea623eb8eb0addd6d36a8cd3fe566)

ich kann leider immernoch nicht ./test_all_notebooks.sh laufen lassen. Da Failed immer das mit der Expression.

2025-01-30 17:23 UTC, ChristianBeilschmidt submitted a review, later dismissed

2025-01-30 17:25 UTC, ChristianBeilschmidt commented
Du hast ja Notebooks angepasst. Kannst du noch irgendwelche aus der Blacklist nehmen?
https://github.com/geo-engine/geoengine-python/blob/e87aac31f357ab34691ad62c025a5562d0a21e52/test_all_notebooks.py#L11

2025-01-31 10:07 UTC, jdroenner commented
https://github.com/geo-engine/geoengine-python/pull/207/commits/dda001f4bf00d0f57005ae4c40e040dabe911bd7 habe noch 3 notebooks aktiviert

2025-01-31 10:08 UTC, ChristianBeilschmidt approved these changes

2025-01-31 10:51 UTC, merged