upload_dataframe method
geo-engine/geoengine-python pull request #9
Opened 2021-07-01 19:48 UTC by michaelmattig

2021-07-01 19:48 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feature-Upload im Python-Paket](https://trello.com/c/zLLlJEUp/238-feature-upload-im-python-paket)

2021-07-02 14:49 UTC, jdroenner requested changes
please add time to the elements in the example / test

2021-07-02 14:49 UTC, jdroenner commented on geoengine/datasets.py
> +from typing import Dict, Union
is Union unused?

2021-07-02 14:49 UTC, jdroenner commented on geoengine/datasets.py
> +        'float64': 'float',
what about the other float types?

2021-07-02 14:49 UTC, jdroenner commented on geoengine/datasets.py
> +        'int64': 'int'
what about other int types?

2021-07-12 15:52 UTC, merged