delete dataset
geo-engine/geoengine-python pull request #95
Opened 2023-01-19 17:15 UTC by michaelmattig

2023-01-19 17:15 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RESPECT] Man kann als Admin öffentliche Datasets in Python wieder löschen](https://trello.com/c/WprlBxBJ/1167-respect-man-kann-als-admin-%C3%B6ffentliche-datasets-in-python-wieder-l%C3%B6schen)

2023-01-20 15:03 UTC, ChristianBeilschmidt requested changes

2023-01-20 15:30 UTC, michaelmattig commented on examples/add_public_raster_dataset.ipynb
> +    "    print(e)"
for me it prints:

> {"error":"Operator","message":"Operator: LoadingInfoError: UnknownDatasetId"}

how do you run your backend?

2023-01-20 16:43 UTC, ChristianBeilschmidt commented on examples/add_public_raster_dataset.ipynb
> +    "    print(e)"
Oh, I just meant the example notebook without running it does not contain the output.

2023-01-20 17:02 UTC, michaelmattig commented on examples/add_public_raster_dataset.ipynb
> +    "    print(e)"
24e878fccd1e0456464c9b7c73f4e83c10f064bd

2023-01-24 17:18 UTC, ChristianBeilschmidt approved these changes

2023-01-24 17:18 UTC, ChristianBeilschmidt commented
bors merge

2023-01-25 09:19 UTC, closed without merging

2023-01-25 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/geo-engine/geoengine-python?pullRequest=95) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/geo-engine/geoengine-python?pullRequest=95) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: michaelmattig<br/>:x: bors[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/geo-engine/geoengine-python?pullRequest=95) it.</sub>